### ISSUE TITLE
Generation is broken

### ISSUE THREAD

**Issue by zaibon** [zero-os/zerotier_client#5]
I try to update the client code by regenerating it with the last version of go-raml but got this error:
```
go-raml client -l python --ramlfile api.raml --dir zerotier 
panic: inline item's properties expect properties in type:map[string]interface{}

goroutine 1 [running]:
github.com/Jumpscale/go-raml/raml.(*Type).createTypeFromPropItems(0xc42015c928, 0xc420180260, 0x11, 0xc42006cb00)
	/home/zaibon/dev/go/src/github.com/Jumpscale/go-raml/raml/types.go:684 +0x601
github.com/Jumpscale/go-raml/raml.(*Type).postProcess(0xc42015c928, 0xc42016ee30, 0xd, 0xc42006cb00, 0x0, 0x0)
	/home/zaibon/dev/go/src/github.com/Jumpscale/go-raml/raml/types.go:649 +0x193
github.com/Jumpscale/go-raml/raml.(*APIDefinition).PostProcess(0xc42006cb00, 0x864ddc, 0x1, 0x7ffc026e19f2, 0x8, 0x0, 0x0)
	/home/zaibon/dev/go/src/github.com/Jumpscale/go-raml/raml/apidefinition.go:133 +0x87a
github.com/Jumpscale/go-raml/raml.ParseReadFile(0x7ffc026e19f2, 0x0, 0x7ffc026e19f2, 0x8, 0xa2ffc0, 0xc42006cb00, 0x410ab8, 0x100, 0x857de0, 0x1, ...)
	/home/zaibon/dev/go/src/github.com/Jumpscale/go-raml/raml/parser.go:140 +0x637
github.com/Jumpscale/go-raml/raml.ParseFile(0x7ffc026e19f2, 0x8, 0xa2ffc0, 0xc42006cb00, 0x78fecc, 0xc4201260a0)
	/home/zaibon/dev/go/src/github.com/Jumpscale/go-raml/raml/parser.go:68 +0x7c
github.com/Jumpscale/go-raml/commands.(*ClientCommand).Execute(0xbf8da0, 0xc4200b78c0, 0x865536)
	/home/zaibon/dev/go/src/github.com/Jumpscale/go-raml/commands/client.go:34 +0x159
main.main.func3(0xc4200b78c0)
	/home/zaibon/dev/go/src/github.com/Jumpscale/go-raml/main.go:166 +0x2d
github.com/Jumpscale/go-raml/vendor/github.com/codegangsta/cli.Command.Run(0x865e98, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8753d5, 0x28, 0x0, ...)
	/home/zaibon/dev/go/src/github.com/Jumpscale/go-raml/vendor/github.com/codegangsta/cli/command.go:137 +0x88a
github.com/Jumpscale/go-raml/vendor/github.com/codegangsta/cli.(*App).Run(0xc4200b7680, 0xc420084080, 0x8, 0x8, 0x0, 0x0)
	/home/zaibon/dev/go/src/github.com/Jumpscale/go-raml/vendor/github.com/codegangsta/cli/app.go:176 +0x8e8
main.main()
	/home/zaibon/dev/go/src/github.com/Jumpscale/go-raml/main.go:256 +0x1839
```

Issue has been created on go-raml repository : https://github.com/Jumpscale/go-raml/issues/309

**Comment by zaibon** [comment]
works fine with https://github.com/Jumpscale/go-raml/commit/3dbbaae227ddf569a2d9b27012d37d5d1c6ae73d
